import React, { useMemo, useState } from 'react';
import { Search, ExternalLink, Copy, ArrowUpRight, ArrowRight, Link2Off, Code2 } from 'lucide-react';
import { ALL_PORTFOLIO_PROJECTS, PORTFOLIO_CATEGORIES } from '../data/portfolioData';

// Generated filler domains are not projects. Original seed references stay available,
// but no live link or delivery claim is shown without independent verification.
const references = ALL_PORTFOLIO_PROJECTS.filter(p => !p.isGenerated);
const serviceForCategory: Record<string, string> = { ecommerce: 'S07', saas: 'S01', medical: 'S01', hospitality: 'S01', education: 'S01' };

export const WorkShowcase: React.FC<{ onOpenEnquiry?: (serviceId?: string) => void }> = ({ onOpenEnquiry }) => {
  const [category, setCategory] = useState('all'); const [subCategory, setSubCategory] = useState('all');
  const [query, setQuery] = useState(''); const [count, setCount] = useState(6); const [feedback, setFeedback] = useState('');
  const filtered = useMemo(() => references.filter(p => (category === 'all' || p.category === category) && (subCategory === 'all' || p.subCategory === subCategory) && `${p.title} ${p.summary} ${p.displayUrl} ${p.techStack.join(' ')} ${p.clientLocation}`.toLowerCase().includes(query.trim().toLowerCase())), [category, subCategory, query]);
  const copy = async (url: string) => { try { await navigator.clipboard.writeText(url); setFeedback('Original URL copied.'); } catch { setFeedback('Clipboard unavailable. Copy the visible URL manually.'); } };
  const reset = () => { setQuery(''); setCategory('all'); setSubCategory('all'); setCount(6); };
  return <section id="work" data-testid="project-showcase" className="border-b border-slate-200 bg-white py-16 sm:py-20">
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div className="flex flex-wrap items-end justify-between gap-6 border-b border-slate-200 pb-7"><div><p className="text-xs font-bold uppercase text-emerald-700">Ideas into working products</p><h2 data-testid="projects-heading" className="mt-3 font-display text-lg font-bold text-slate-900">Project architecture library</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-600">Explore project types, technology and scope across industries. Original client links are shown only when verified.</p></div><span data-testid="project-library-count" className="text-sm font-semibold text-slate-600">{references.length} references · 10 industries</span></div>
      <p data-testid="project-verification-notice" className="mt-5 border-l-2 border-amber-400 pl-3 text-sm leading-relaxed text-slate-600">The imported examples contain unverified project names and URLs. These are architecture references, not verified client deliveries. Public project links are currently unavailable.</p>
      <div className="my-6 grid gap-3 md:grid-cols-[minmax(0,1fr)_250px_230px]"><div className="relative"><Search size={18} className="absolute left-3 top-3.5 text-slate-400" /><input data-testid="project-search" aria-label="Search projects" value={query} onChange={e => { setQuery(e.target.value); setCount(6); }} placeholder="Search projects, industries or technology" className="w-full rounded-lg border border-slate-200 py-3 pl-10 pr-4 text-sm focus:border-indigo-500 focus:outline-none" /></div><select data-testid="project-category-filter" aria-label="Industry" value={category} onChange={e => { setCategory(e.target.value); setSubCategory('all'); setCount(6); }} className="rounded-lg border border-slate-200 bg-white p-3 text-sm"><option value="all">All industries</option>{PORTFOLIO_CATEGORIES.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select data-testid="project-subcategory-filter" aria-label="Project type" value={subCategory} disabled={category === 'all'} onChange={e => { setSubCategory(e.target.value); setCount(6); }} className="rounded-lg border border-slate-200 bg-white p-3 text-sm disabled:opacity-50"><option value="all">All project types</option>{PORTFOLIO_CATEGORIES.find(c => c.id === category)?.subcategories.map(s => <option key={s}>{s}</option>)}</select></div>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><p data-testid="project-results-count" className="text-sm text-slate-500">{filtered.length} matching references</p><button data-testid="project-reset-filters" onClick={reset} className="text-sm font-semibold text-indigo-700 hover:underline">Reset filters</button></div>
      {feedback && <p data-testid="project-link-feedback" role="status" className="mb-4 text-sm text-emerald-700">{feedback}</p>}
      {filtered.length === 0 ? <p data-testid="project-empty-results" className="py-12 text-center text-slate-600">No references match your search.</p> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.slice(0, count).map((p, i) => <article key={p.id} data-testid={`project-card-${p.id}`} className="group flex flex-col rounded-lg border border-slate-200 bg-white transition-colors hover:border-indigo-300">
        <div className={`flex items-center justify-between gap-3 border-b border-slate-100 px-5 py-4 ${i % 3 === 0 ? 'bg-emerald-50' : i % 3 === 1 ? 'bg-indigo-50' : 'bg-sky-50'}`}><div className="flex items-center gap-2 text-xs font-semibold text-slate-700"><Code2 size={17} className="shrink-0" />{p.subCategory}</div><span className="shrink-0 font-mono text-xs text-slate-500">REFERENCE</span></div>
        <div className="flex flex-1 flex-col p-5"><h3 className="font-display text-lg font-semibold leading-snug text-slate-900">{p.title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{p.summary}</p><div className="mt-4 flex flex-wrap gap-2">{p.techStack.slice(0, 4).map(t => <span key={t} className="rounded border border-slate-200 px-2 py-1 text-[11px] text-slate-600">{t}</span>)}</div><div className="mt-auto pt-6">
          {p.urlVerified && p.originalUrl && /^https:\/\//.test(p.originalUrl) ? <><a data-testid={`project-original-url-${p.id}`} href={p.originalUrl} target="_blank" rel="noopener noreferrer" className="flex items-center justify-between gap-2 break-all text-sm font-semibold text-indigo-700">{p.originalUrl}<ExternalLink size={16} className="shrink-0" /></a><button data-testid={`project-copy-url-${p.id}`} onClick={() => copy(p.originalUrl!)} className="mt-2 inline-flex items-center gap-2 text-xs text-slate-600"><Copy size={14} />Copy original URL</button></> : <div data-testid={`project-url-unavailable-${p.id}`} className="border-t border-slate-100 pt-4"><p className="flex items-center gap-2 text-xs font-semibold text-amber-800"><Link2Off size={14} className="shrink-0" />Original URL unavailable / unverified</p><p className="mt-2 break-all font-mono text-[11px] text-slate-500">Source reference: {p.displayUrl}</p></div>}
          <button data-testid={`project-build-similar-${p.id}`} onClick={() => onOpenEnquiry?.(serviceForCategory[p.category] || 'S01')} className="mt-4 flex w-full items-center justify-between gap-2 rounded-lg bg-slate-900 px-4 py-3 text-sm font-semibold text-white transition-colors hover:bg-indigo-700">Discuss a similar project<ArrowUpRight size={17} className="shrink-0" /></button>
        </div></div>
      </article>)}</div>}
      {count < filtered.length && <div className="mt-8 text-center"><button data-testid="project-load-more" onClick={() => setCount(count + 6)} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50">More references<ArrowRight size={16} /></button></div>}
    </div>
  </section>;
};