import React, { useCallback, useEffect, useState } from 'react';
import { apiFetch, API_BASE } from '../../api';
import { Button } from '../ui/button';
import { RefreshCw, Play, Pause, Download } from 'lucide-react';

const endpoints: Record<string, string> = { pipeline: '/api/pipeline/status', freelancers: '/api/admin/freelancers', facts: '/api/facts' };
export const AdminOperations = ({ tab }: { tab: string }) => {
  const [data, setData] = useState<any>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async (signal?: AbortSignal) => { if (!endpoints[tab]) return; setError(''); try { const r = await apiFetch(endpoints[tab], { signal }); if (!r.ok) throw new Error(); const result = await r.json(); if (!signal?.aborted) setData(result); } catch { if (!signal?.aborted) setError('Could not load records. Please retry.'); } }, [tab]);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load]);
  const action = async (path: string, body?: any, method = 'POST') => { setBusy(true); setError(''); try { const r = await apiFetch(path, { method, headers: { 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); if (!r.ok) throw new Error(); await load(); } catch { setError('Action failed. Please retry.'); } finally { setBusy(false); } };
  return <section data-testid={`admin-${tab}-panel`} className="space-y-5">{error && <p data-testid="admin-operations-error" role="alert" className="text-sm text-rose-700">{error}</p>}{tab !== 'exports' && <Button data-testid="admin-operations-refresh" variant="outline" onClick={() => load()}><RefreshCw />Refresh</Button>}
    {tab === 'pipeline' && data && <><h2 className="font-display text-lg font-bold">Page generation pipeline</h2><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{[['Generated', data.generatedSoFar], ['Approved', data.approvedCount], ['Needs review', data.needsReviewCount], ['Target', data.totalTarget]].map(([label, value]) => <div key={label} className="border-l-2 border-indigo-200 pl-4"><p className="text-xs text-slate-500">{label}</p><p data-testid={`pipeline-metric-${String(label).toLowerCase().replace(' ', '-')}`} className="mt-2 text-2xl font-bold">{Number(value).toLocaleString()}</p></div>)}</div><p data-testid="pipeline-status" className="text-sm text-slate-600">Status: {data.status}</p><div className="flex flex-wrap gap-3">{[500, 2500].map(count => <Button data-testid={`pipeline-run-${count}`} key={count} disabled={busy} onClick={() => action('/api/pipeline/run', { count })}><Play />Generate {count}</Button>)}<Button data-testid="pipeline-pause" variant="outline" disabled={busy} onClick={() => action('/api/pipeline/pause')}><Pause />Pause</Button></div></>}
    {tab === 'freelancers' && <><h2 className="font-display text-lg font-bold">Specialist moderation</h2><div className="grid gap-4 md:grid-cols-2">{data?.freelancers.map((profile: any) => <article key={profile.id} className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="font-semibold">{profile.displayName}</h3><p className="mt-2 text-sm text-slate-600">{profile.bio}</p><p data-testid={`freelancer-state-${profile.id}`} className="my-3 text-xs font-semibold text-indigo-700">{profile.profileState}</p><Button data-testid={`freelancer-moderate-${profile.id}`} variant="outline" disabled={busy} onClick={() => action(`/api/freelancers/${profile.id}/moderate`, { state: profile.profileState === 'approved' ? 'suspended' : 'approved' }, 'PATCH')}>{profile.profileState === 'approved' ? 'Suspend Profile' : 'Approve Profile'}</Button></article>)}</div></>}
    {tab === 'facts' && <><h2 className="font-display text-lg font-bold">Business facts registry</h2><div className="divide-y divide-slate-200">{data?.facts.map((f: any) => <div key={f.key} className="py-4"><h3 className="font-semibold">{f.label}</h3><p data-testid={`business-fact-${f.key}`} className="mt-1 text-sm text-slate-600">{f.value}</p><p className="mt-2 text-xs text-slate-500">{f.source} · {f.approvalStatus}</p></div>)}</div></>}
    {tab === 'exports' && <><h2 className="font-display text-lg font-bold">Data & sitemap exports</h2><div className="grid gap-3 sm:grid-cols-2">{[['locations-manifest.csv', '/api/exports/locations-manifest.csv'], ['pages-manifest.csv', '/api/exports/pages-manifest.csv'], ['completion-report.json', '/api/exports/completion-report.json'], ['sitemap.xml', '/api/sitemap.xml']].map(([name, path]) => <a key={name} data-testid={`admin-export-${name.split('.')[0]}`} href={`${API_BASE}${path}`} target="_blank" rel="noreferrer" className="admin-link justify-between rounded-lg border border-slate-200 bg-white p-4">{name}<Download size={16} /></a>)}</div></>}
  </section>;
};